plank_constant: 6.62607015e-34
dt: 0.1
fps: 60
electron:
  x: 0
  y: 0
  vx: 0.01
  vy: 0
  radius: 0.1
  energy: 0.5
  color: 0x0000ff
photon:
  x: -0.5
  y: 0
  vx: 0
  vy: 0
  radius: 0.05
  energy: 0.5
  color: 0xffff00
background_color: 0x000000
line_color: 0x00ff00
